### ISSUE TITLE
Org Name

### ISSUE THREAD

**Issue by Arttii** [Arttii/malefico#10]
Issue tracking a new organization name.

@kszucs

**Comment by kszucs** [comment]
All of our project names are taken.

**Comment by kszucs** [comment]
Daskos is free BTW. We can rename dask.mesos -> daskos.
Thoughts?

**Comment by kszucs** [comment]
I've created it, we can rename later.

**Comment by Arttii** [comment]
daskos sounds good. Did we decide on an org name I cant remember.

**Comment by kszucs** [comment]
I can't recall :)

**Comment by kszucs** [comment]
I've transferred the related repos. Should we rename satyr -> mentor?

**Comment by kszucs** [comment]
I've created the placeholders for mentor/daskos/epos and added You as a maintainer on PyPI

**Comment by kszucs** [comment]
Please transfer mentos unders daskos too.

**Comment by Arttii** [comment]
sure Ill do it in a bit

**Comment by Arttii** [comment]
Could you make me an owner(maintainer) on the org as well?

**Comment by kszucs** [comment]
Done.

**Comment by Arttii** [comment]
so moved andd travis is rebuilding. Should we make one shared pypi  account(mentos?) for the builds you think?
