### ISSUE TITLE
Another name

### ISSUE THREAD

**Issue by kszucs** [Arttii/malefico#4]
Malefico isn't easily memorizable. It's not intuitive and I don't know the meaning of it (is it italian https://translate.google.com/#auto/en/malefico or a character?)
Satyr's name also odd, difficult to find. 

I think malefico should be renamed to suggest "it's a native mesos client". Satyr should be renamed to suggest "it's a high level mesos framework". Ideas?

Do You have other names or you insist on malefico?

**Comment by kszucs** [comment]
Mythos, pymesos, pysos, meson, mesos, mysos are taken, what about pythos?

**Comment by Arttii** [comment]
Malefico is Latin for dangerous/evil, which was meant to reflect the state of the project at the time. I'm not married to it, it just an experimental name i use sometimes.

I do not know to be honest. I am all for the Zen of Python, but I sometimes find it more useful when a package has an interesting name that actually means something. Plus, considering the fact that almost all puns on py+-mesos are basically taken, being descriptive is getting hard. To that end Mesos also kinda does not mean much. The same for Fenzo and Dask even I guess.

There is always mesos-python, but I think that's a bit boring. Could work for malefico, but not satyr I think. I, for example, liked the name satyr. We could do variations of that maybe? Not so sure. In my company we usually describe, what the project does and try to find a German word, that condenses the sentence to one word.

Dammit naming things :D

**Comment by Arttii** [comment]
Actually ha @kszucs http://wh40k.lexicanum.com/wiki/Pythos :D. Not bad I guess.

**Comment by Arttii** [comment]
- mesos-driver
- mesos-treiber
- treiber
- mesos-client 
- mesos-python
- mesa =P ?

**Comment by kszucs** [comment]
Mentor? https://en.wikipedia.org/wiki/Mentor_(Odyssey) 
Methos?
Mentos maybe? :)

Pythos' edit distance from python is only 1, confusing

**Comment by kszucs** [comment]
cc @lazerviking (co-founder of Satyr) ideas?

**Comment by Arttii** [comment]
Mentor I like, could stay in the entire Greek thematic. But, I think its a better name for Satyr if we still want to change it as well.
Mentos could be amazing tbh.

**Comment by kszucs** [comment]
I took a look at the source code, great work @Arttii . 

Naming could be:
   Malefico -> mentos : https://www.youtube.com/watch?v=boWPgICPLQo
   Satyr -> mentor
   dask.mesos -> daskos
   Epos -> epos  (workflow manageer based on dask.mesos)

Or organizing around poetry (https://en.wikipedia.org/wiki/Epic_poetry)
   there are a lot of characters too: https://en.wikipedia.org/wiki/Odyssey
   malefico -> medias (in medias res, mesos meaning is similar)
   satyr -> mentor or satyr  (as a mythical creature)
   dask.mesos -> daskos 
   epos -> epos

A last one: Mytos, Satyr, Daskos, Epos

Or merge malefico and satyr -> mentos, daskos, epos

Naming stuff is blocking my mind...

**Comment by kszucs** [comment]
mesos + schedule:  schedos, medule[r] 

mesos + resource:  mesrc, resrc

**Comment by Arttii** [comment]
I think im sold on mentos and mentor. And I would like to keep satyr and mentos separate, would be easier to experiment. Any thoughts on the org? Mesos-kit ?

**Comment by nz87** [comment]
And then you should do mentos-coke, a tool that uses up all of mesos' resources and then some. :D

**Comment by Arttii** [comment]
Oh god...If Mentos Corp does not sue us could be amazing. Also funny thing is it makes sense, the Mentos name,with the reconnect resubscribe think were trying to have the Mesos freshness that never stops. Plus apparently hard to kill.

Not making any statement on the stability :D. But could be smth to aspire to.

**Comment by kszucs** [comment]
I've registered the mentos package on PyPI. What is your account?

**Comment by Arttii** [comment]
@kszucs arttii. I also have some progress on the satyr integration with attr, its slightly magic though.

**Comment by kszucs** [comment]
I've added You.

**Comment by Arttii** [comment]
Should we look into adding a release. Any ideas on proper versioning and releases? Also tests.

I think we should close this issue and move the discussion, such as tests, first release, org to separate issues?
