### ISSUE TITLE
Collaborator request

### ISSUE THREAD

**Issue by kszucs** [Arttii/malefico#7]
Can You add me as an outside collaborator?

I'd create a drone CI integration.

**Comment by Arttii** [comment]
Sure, I thought we were going to wait to migrate to the new org? Also the proper version is inside the refactor branch right now.

**Comment by kszucs** [comment]
Any ideas about naming the org?

**Comment by Arttii** [comment]
I finished the refactor, the api stayed the same, but the internals are now much nicer. Proper debug logs and warn logs in place as well as fairly solid reconnect logic.

Dunno, we could go for something like boring like mesos-python, mesos-py. God naming things.

I am going to close this, as I added you the list. Are you reachable on gitter so we can chat more easily? Should I just go for private?

**Comment by Arttii** [comment]
Or maybe something like mesos-kit not sure. Or something inspired by mesosphere perhaps?
